// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thurwzvfpoijnkhlvsiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRodXJ3enZmcG9pam5raGx2c2l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MTQ1MzksImV4cCI6MjA2MTA5MDUzOX0.5XVL8aYt3tUIMqfoV8v8loekLiUgnsxh3pFqEZb9VMs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);